---
cpu_count: '2'
memory_size: '1024'
disk_size: '10140'
disk_format: VDI
hostiocache: 'on'
os_type_id: Ubuntu
boot_wait: '0'
boot_cmd_sequence: []
ssh_login_timeout: '10000'
ssh_user: root
ssh_password: vagrant
ssh_key: ''
ssh_host_port: '7222'
ssh_guest_port: '22'
sudo_cmd: bash '%f'
shutdown_cmd: poweroff
postinstall_files:
- libexec/veewee.sh
postinstall_timeout: '10000'
